#ifndef _ORTE_HDCLIENT_CONSTANTS_H
#define _ORTE_HDCLIENT_CONSTANTS_H

#define YARN_PB_FILE_ENV_KEY "YARN_PB_FILE"
#define AM_UMBILICAL_PORT_ENV_KEY "AM_UMBILICAL_PORT"
#define HAMSTER_HANDSHAKE "hamster-001"

#endif